<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@3.3">
  <node class="cps.n.StepAtomNode" plugin="workflow-cps@2.74">
    <parentIds>
      <string>10</string>
    </parentIds>
    <id>11</id>
    <descriptorId>org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep</descriptorId>
  </node>
  <actions>
    <cps.a.ArgumentsActionImpl plugin="workflow-cps@2.74">
      <arguments>
        <entry>
          <string>script</string>
          <string>
cat &lt;&lt;EOT &gt; /var/lib/jenkins/workspace/vm_detailspecific/roles/vm_detail/files/server_ip.txt
$VCenter_Hostname
EOT
cat &lt;&lt;EOT &gt; /var/lib/jenkins/workspace/vm_detailspecific/roles/vm_detail/files/hosts.txt
$VCentre_Username
$VCentre_Password
EOT
cat &lt;&lt;EOT &gt; /var/lib/jenkins/workspace/vm_detailspecific/roles/vm_detail/files/vm_name.txt
$VM_Name
EOT
vm_value=&quot;$(cat /var/lib/jenkins/workspace/vm_detailspecific/roles/vm_detail/files/vm_name.txt | tr -s &apos; &apos; | cut -d &apos; &apos; -f 2 | tr &apos;
&apos; &apos;,&apos; | sed &apos;s/,$//&apos;)&quot;
echo &quot;$vm_value&quot; &gt; vm_specific.txt
</string>
        </entry>
      </arguments>
      <isUnmodifiedBySanitization>true</isUnmodifiedBySanitization>
    </cps.a.ArgumentsActionImpl>
    <wf.a.TimingAction plugin="workflow-api@2.37">
      <startTime>1576580110642</startTime>
    </wf.a.TimingAction>
    <s.a.LogStorageAction/>
    <wf.a.ErrorAction plugin="workflow-api@2.37">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 1</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:658)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:604)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:548)</trace>
          <trace>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</trace>
          <trace>java.util.concurrent.FutureTask.run(FutureTask.java:266)</trace>
          <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)</trace>
          <trace>java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)</trace>
          <trace>java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)</trace>
          <trace>java.lang.Thread.run(Thread.java:748)</trace>
        </stackTrace>
        <suppressedExceptions class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
          <c class="list"/>
          <list reference="../c"/>
        </suppressedExceptions>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>